# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

markdown: kramdown

# Local version
#theme: jekyll-theme-feeling-responsive
#plugins:
#  - jekyll-feed
# or remote version
remote_theme: Phlow/feeling-responsive@gh-pages
plugins:
  - jekyll-feed
  - jekyll-remote-theme
 
# For feeling-responsive
title: "Virtual History Title"
slogan: "Virtual History Slogan"
description: "About this site: Das Projekt Virtual History will am Beispiel des antiken Forum Romanum in Rom zeigen, wie eine digitale Aufbereitung aktueller Forschungsergebnisse im Medium VR völlig neue sinnlich-intellektuelle Erfahrungen ermöglicht."
#urlimg: "/images/"
urlimg: "https://virtualhistory.github.io/Website/images"
 
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
