# Virtual History Website Configuration


# Local version ###############################################################
theme: jekyll-theme-feeling-responsive
plugins:
  - jekyll-feed
urlimg: "/images/"
# or remote version ###########################################################
#remote_theme: Phlow/feeling-responsive@gh-pages
#plugins:
#  - jekyll-feed
#  - jekyll-remote-theme
#urlimg: "https://virtualhistory.github.io/Website/images/"
############################################################################### 

markdown: kramdown

# For feeling-responsive
title: "Virtual History Title"
slogan: "Virtual History Slogan"
description: "About this site: Das Projekt Virtual History will am Beispiel des antiken Forum Romanum in Rom zeigen, wie eine digitale Aufbereitung aktueller Forschungsergebnisse im Medium VR völlig neue sinnlich-intellektuelle Erfahrungen ermöglicht."
logo: logo.png

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
